### ISSUE TITLE
Version in "./docker-compose.yml" is unsupported.

### ISSUE THREAD

**Issue by rostgoat** [blueimp/wdio#1]
cloned repo, ran the chrome command `docker-compose run --rm wdio chrome` and got this message in  terminal:

```
docker-compose run --rm wdio chrome 
/home/matthew/.local/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.24.1) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

```
is there an instruction I am missing here?

Docker version 18.06.1-ce
Node 8.10.0
npm 6.9.0
Ubuntu 18.04.1 LTS

**Comment by blueimp** [comment]
Looks like you have an older `docker-compose` version that doesn't support yet the [docker-compose file](https://docs.docker.com/compose/compose-file/) version `3.7`.

You can safely change the version at the top of [docker-compose.yml](https://github.com/blueimp/wdio/blob/master/docker-compose.yml) to `2.2`, since this version also supports all the directives used in the file:
```yml
version: '2.2'
```

**Comment by rostgoat** [comment]
cool thanks that works
